# Generated by Django 5.2.4 on 2025-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbpost',
            name='author',
            field=models.CharField(default='pramod', max_length=100),
        ),
    ]
