# Generated by Django 5.2.4 on 2025-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_blogbpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogbpost',
            name='published',
        ),
        migrations.AddField(
            model_name='blogbpost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
