# Generated by Django 5.2.4 on 2025-08-09 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_remove_blogbpost_published_blogbpost_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
